export const topics = [
  // Algebra
  {
    id: "b6-15",
    title: "B6-15 Rational Expressions: Basic Simplifying of Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=67TWacRscV0&index=82&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b6-16",
    title: "B6-16 Rational Expressions: Introducing Simplifying Algebraic Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=JLueXZuWYP0&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=83",
    completed: false,
  },
  {
    id: "b6-17",
    title: "B6-17 Rational Expressions: Examples of Simplifying Algebraic Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=RY7UP_3spZo&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=84",
    completed: false,
  },
  {
    id: "b6-18",
    title: "B6-18 Rational Expressions: Basic Adding and Subtracting Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=_lukNbIWCPU&feature=youtu.be",
    completed: false,
  },
  {
    id: "b6-19",
    title: "B6-19 Rational Expressions: Examples of Adding / Subtracting Algebraic Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=JsYC1lI2zCI&index=86&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b6-20",
    title: "B6-20 Rational Expressions: Simplifying using Polynomial Division",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=LAph0F14sNA&index=87&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b7-05",
    title: "B7-05 Graphs: Introducing the Modulus Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=sWlo7qZPFsw&index=92&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b7-06",
    title: "B7-06 Graphs: Sketching the Modulus of a Linear Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=OWWtZ1vT0Ik&feature=youtu.be",
    completed: false,
  },
  {
    id: "b7-07",
    title: "B7-07 Graphs: Examples of Sketching the Modulus of a Linear Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=koTYdxmhJoE",
    completed: false,
  },
  {
    id: "b7-08",
    title: "B7-08 Graphs: Solving Modulus Equations",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=5q0dkBShi7Y",
    completed: false,
  },
  {
    id: "b7-09",
    title: "B7-09 Graphs: Examples of Solving Modulus Equations",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=_PjZb15JHf8",
    completed: false,
  },
  {
    id: "b7-10",
    title: "B7-10 Graphs: Solving Modulus Inequalities",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=kajCu-FeNvQ&index=96&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b7-11",
    title: "B7-11 Graphs: Writing a Modulus Inequality in a form without the Modulus",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=KfyvUdJAczA",
    completed: false,
  },
  {
    id: "b7-12",
    title: "B7-12 Graphs: Examples of Solving Basic Modulus Inequalities",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=kpDB7s1dclA",
    completed: false,
  },
  {
    id: "b7-13",
    title: "B7-13 Graphs: Writing an Inequality in a form with a Modulus",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=WsMuvyxryRo",
    completed: false,
  },
  {
    id: "b7-14",
    title: "B7-14 Graphs: Examples of Writing Inequalities in a form with a Modulus",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=-L9qcdVPe1Q",
    completed: false,
  },
  {
    id: "b7-15",
    title: "B7-15 Graphs: 3 Methods of Writing an Inequality in a form with a Modulus",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=r2CL3mmBDDs",
    completed: false,
  },
  {
    id: "b7-16",
    title: "B7-16 Graphs: Sketching the Modulus of Other Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=B2mui1CLUAU&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=97",
    completed: false,
  },
  {
    id: "b7-17",
    title: "B7-17 Graphs: Sketching y=f(|x|)",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=KgfwepvSm0k&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=98",
    completed: false,
  },
  {
    id: "b8-01",
    title: "B8-01 Functions: What is a Function?",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=MrOCHA8qnDo&index=111&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-02",
    title: "B8-02 Functions: Introducing the Domain and Range of a Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=Kc-fVGvPRQg&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=112",
    completed: false,
  },
  {
    id: "b8-03",
    title: "B8-03 Functions: Examples of Finding the Domain and Range",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=Ty4P3mJ5h8g&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=113",
    completed: false,
  },
  {
    id: "b8-04",
    title: "B8-04 Functions: One-to-One, Many-to-One, One-to-Many, Many-to-Many",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=abB9rWbOdUw&index=114&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-05",
    title: "B8-05 Functions: Restricting the Domain",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=856Jmr6OixI&index=115&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-06",
    title: "B8-06 Functions: The Range of Modulus Functions",
    category: "algebra",
    url: "https://youtu.be/ZDgaoO6IoPw",
    completed: false,
  },
  {
    id: "b8-07",
    title: "B8-07 Functions: Even & Odd Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=Q_ZmmbqzA1c&index=116&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-08",
    title: "B8-08 Functions: Introducing Composite Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=6IWs2zwBIEc&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=117",
    completed: false,
  },
  {
    id: "b8-09",
    title: "B8-09 Functions: Examples of Composite Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=zzXcnOBzbxg&index=118&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-10",
    title: "B8-10 Functions: The Domain of a Composite Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=O_vTJGFGWd4&index=119&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-11",
    title: "B8-11 Functions: Introducing Inverse Functions and Restricting the Domain",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=PFyN9_DI95U&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=120",
    completed: false,
  },
  {
    id: "b8-12",
    title: "B8-12 Functions: Finding an Inverse Function",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=_j_l9-YflWc&index=121&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-13",
    title: "B8-13 Functions: Examples of finding Inverse Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=EoRTSJ0qJjQ&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=122",
    completed: false,
  },
  {
    id: "b8-14",
    title: "B8-14 Functions: A Consequence of Inverse Functions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=q4SkUfGB7kc&index=123&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-",
    completed: false,
  },
  {
    id: "b8-15",
    title: "B8-15 Functions: Domain and Range of an Inverse Function",
    category: "algebra",
    url: "https://youtu.be/5R1nu8rLees",
    completed: false,
  },
  {
    id: "b8-16",
    title: "B8-16 Functions: Set Notation for Domain and Range",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=RAu8ee0Rw_0",
    completed: false,
  },
  {
    id: "b8-17",
    title: "B8-17 Functions: Interval Notation for Domain and Range",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=NYsvcgvMEQc",
    completed: false,
  },
  {
    id: "b9-21",
    title: "B9-21 Graph Transformations: Combining Transformations - Does the Order Matter?",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=lokEdLotXT4&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=145&t=3s",
    completed: false,
  },
  {
    id: "b9-22",
    title: "B9-22 Graph Transformations: Examples of Describing Two Transformations",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=Q0kPb21Bzrs&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=146",
    completed: false,
  },
  {
    id: "b9-23",
    title: "B9-23 Graph Transformations: Examples of Two Transformations of y = x(x - 2)",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=2JFK8mF2PsQ",
    completed: false,
  },
  {
    id: "b9-24",
    title: "B9-24 Graph Transformations: Examples of Two Transformations of y = arccos(x)",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=IBw5X0sq3eU&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=148",
    completed: false,
  },
  {
    id: "b9-25",
    title: "B9-25 Graph Transformations: Two Transformations via ‘Replacing’",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=qqPmiNFq3Ok&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=149",
    completed: false,
  },
  {
    id: "b9-26",
    title: "B9-26 Graph Transformations: Using BIDMAS",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=30yvaggnEGs",
    completed: false,
  },
  {
    id: "b10-01",
    title: "B10-01 Algebraic Fractions: Proper Fractions & Improper Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=ws7BXAG_z5A&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=150",
    completed: false,
  },
  {
    id: "b10-02",
    title: "B10-02 Algebraic Fractions: Adding and Subtracting Algebraic Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=WXRykd0u3Z4&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=151",
    completed: false,
  },
  {
    id: "b10-03",
    title: "B10-03 Algebraic Fractions: Introducing Partial Fractions via Substitution",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=0Qdf8lYpWng&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=152",
    completed: false,
  },
  {
    id: "b10-04",
    title: "B10-04 Algebraic Fractions: Partial Fractions via Comparing Coefficients",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=rbK5jrsweVY&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=153",
    completed: false,
  },
  {
    id: "b10-05",
    title: "B10-05 Algebraic Fractions: Examples of Partial Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=rQGhpxV5TW4&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=154",
    completed: false,
  },
  {
    id: "b10-06",
    title: "B10-06 Algebraic Fractions: THREE Partial Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=kHu3UrLjuck",
    completed: false,
  },
  {
    id: "b10-07",
    title: "B10-07 Algebraic Fractions: Examples of THREE Partial Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=LNKAIo3weUc",
    completed: false,
  },
  {
    id: "b10-08",
    title: "B10-08 Algebraic Fractions: How we deal with Repeated Factors in the Denominator",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=vwo8-_OIyKQ",
    completed: false,
  },
  {
    id: "b10-09",
    title: "B10-09 Algebraic Fractions: Examples of Repeated Factors in the Denominator",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=SkWaMMBLAPg",
    completed: false,
  },
  {
    id: "b10-10",
    title: "B10-10 Algebraic Fractions: EXTENSION Quadratic Terms in the Denominator",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=c7mc7ueX2QE",
    completed: false,
  },
  {
    id: "b10-11",
    title: "B10-11 Algebraic Fractions: EXTENSION Examples of Quadratics in the Denominator",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=3X8SvGWjcgg",
    completed: false,
  },
  {
    id: "b10-12",
    title: "B10-12 Algebraic Fractions: EXTENSION How we deal with Improper Fractions",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=xqlqKSPSEHo",
    completed: false,
  },
  {
    id: "b10-13",
    title: "B10-13 Algebraic Fractions: Partial Fractions with Binomial Expansion",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=1_otnM0GwTc",
    completed: false,
  },
  {
    id: "b10-14",
    title: "B10-14 Algebraic Fractions: Partial Fractions with Integration",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=n9W6az7jfso",
    completed: false,
  },
  {
    id: "b11-00",
    title: "B11-00 Introduction to Modelling",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=BLbR0SWFqdw",
    completed: false,
  },
  {
    id: "b11-01",
    title: "B11-01 Modelling: The Microbiologist Problem",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=QSzm6gRYsHA",
    completed: false,
  },
  {
    id: "b11-02",
    title: "B11-02 Modelling: The Fish in a Lake Problem",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=Pf-rZXVLTpc",
    completed: false,
  },
  {
    id: "b11-03",
    title: "B11-03 Modelling: The Playground Problem",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=3j4Is_f72Tw",
    completed: false,
  },
  {
    id: "b11-04",
    title: "B11-04 Modelling: The Football Problem",
    category: "algebra",
    url: "https://www.youtube.com/watch?v=GYESlLp7tEw",
    completed: false,
  },

  // Coordinate geometry in the (x,y) plane
  {
    id: "c3-01",
    title: "C3-01 Parametric Equations: Introducing Parametric Equations",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=Y0egyRdVWL8",
    completed: false,
  },
  {
    id: "c3-02",
    title: "C3-02 Parametric Equations: The Difference between Cartesian & Parametric",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=aGH61Go4bTs",
    completed: false,
  },
  {
    id: "c3-03",
    title: "C3-03 Parametric Equations: Cartesian to Parametric",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=W6RFR8opLhk",
    completed: false,
  },
  {
    id: "c3-04",
    title: "C3-04 Parametric Equations: Find where x=t^3-4t, y=t^2+t meets y=20",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=13m5Ffm12bg",
    completed: false,
  },
  {
    id: "c3-05",
    title: "C3-05 Parametric Equations: What does x=t^3-4t, y=t^2+t look like?",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=pzT3pnYqu7g",
    completed: false,
  },
  {
    id: "c3-06",
    title: "C3-06 Parametric Equations: What does x=2sin(t), y=4cos(t-pi/4) look like?",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=KI_v_zQfVAs",
    completed: false,
  },
  {
    id: "c3-07",
    title: "C3-07 Parametric Equations: Parametric to Cartesian",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=bIigy1O5euE",
    completed: false,
  },
  {
    id: "c3-08",
    title: "C3-08 Parametric Equations: Defining an Ellipse Parametrically",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=lvsy9Ksvq3I",
    completed: false,
  },
  {
    id: "c4-01",
    title: "C4-01 Parametric Equation Modelling: Parametric to Cartesian",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=rNjReqMCNaQ",
    completed: false,
  },
  {
    id: "c4-02",
    title: "C4-02 Parametric Equation Modelling: A Projectiles Problem",
    category: "coordinate geometry in the (x,y) plane",
    url: "https://www.youtube.com/watch?v=Igv-vlYwYHA",
    completed: false,
  },

  // Sequences & series
  {
    id: "d1-19",
    title: "D1-19 Binomial Expansion: EXTENSION Extending Binomial Expansion",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=tykyacXWqho",
    completed: false,
  },
  {
    id: "d1-20",
    title: "D1-20 Binomial Expansion: Writing (a + bx)^n in the form p(1 + qx)^n",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=VKCWY8sZsNQ",
    completed: false,
  },
  {
    id: "d1-21",
    title: "D1-21 Binomial Expansion: Find the first four terms of (1 + x)^(-1)",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=orkTMVDJios",
    completed: false,
  },
  {
    id: "d1-22",
    title: "D1-22 Binomial Expansion: Find the first four terms of (1 + 2x)^(-2)",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=tVcH1LDCUy0",
    completed: false,
  },
  {
    id: "d1-23",
    title: "D1-23 Binomial Expansion: Find the first four terms of (1 - 3x)^(-3)",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=yyy1w2vfYGk",
    completed: false,
  },
  {
    id: "d1-24",
    title: "D1-24 Binomial Expansion: Find the first four terms of (2 + 4x)^(-5)",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Dbt7OsiThno",
    completed: false,
  },
  {
    id: "d1-25",
    title: "D1-25 Binomial Expansion: Find the first four terms of (9 - 3x)^(1/2)",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=uVpZBr57NqQ",
    completed: false,
  },
  {
    id: "d1-26",
    title: "D1-26 Binomial Expansion: Introducing the Range of Validity",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=9jHo7X-_1As",
    completed: false,
  },
  {
    id: "d1-27",
    title: "D1-27 Binomial Expansion: Examples on Determining the Range of Validity",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Xij6C-I89rs",
    completed: false,
  },
  {
    id: "d1-28",
    title: "D1-28 Binomial Expansion: Two Trickier Binomial Expansions",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=JftikC_muVs",
    completed: false,
  },
  {
    id: "d1-29",
    title: "D1-29 Binomial Expansion: Two Trickier Range of Validity",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=FmUZ2cgCuJY",
    completed: false,
  },
  {
    id: "d1-30",
    title: "D1-30 Binomial Expansion: New Formula, Old Question",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=4bqel9PpwVg",
    completed: false,
  },
  {
    id: "d1-31",
    title: "D1-31 Binomial Expansion: Evaluating",
    category: "sequences & series",
    url: "https://youtu.be/6X1QC3ZYWPM",
    completed: false,
  },
  {
    id: "d2-01",
    title: "D2-01 Sequences: GCSE Revision on Linear and Quadratic Sequences",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=PCBTjC_MIck",
    completed: false,
  },
  {
    id: "d2-02",
    title: "D2-02 Sequences: Inductive Definitions and Recurrence Relations",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=TZbZtm-WT_o",
    completed: false,
  },
  {
    id: "d2-03",
    title: "D2-03 Sequences: Finding the First Five Terms of an Inductive Definition",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=XMFi0PCaAG8",
    completed: false,
  },
  {
    id: "d2-04",
    title: "D2-04 Sequences: EXTENSION The Logistic Map",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=41HgtSc67rA",
    completed: false,
  },
  {
    id: "d2-05",
    title: "D2-05 Sequences: Investigating Limits of Inductive Definitions",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=0SjTs3QfiO8",
    completed: false,
  },
  {
    id: "d2-06",
    title: "D2-06 Sequences: Describing Sequences",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=iyzc0tIWWBM",
    completed: false,
  },
  {
    id: "d3-01",
    title: "D3-01 Sigma Notation: Introducing Sigma Notation",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=wkdMcYfknw8",
    completed: false,
  },
  {
    id: "d3-02",
    title: "D3-02 Sigma Notation: Writing a Series in Sigma Notation",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=_NokHKXHLy8",
    completed: false,
  },
  {
    id: "d3-03",
    title: "D3-03 Sigma Notation: Examples of Evaluating Series",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=kV0fj4-z_8Q",
    completed: false,
  },
  {
    id: "d3-04",
    title: "D3-04 Sigma Notation: When to Expand Brackets and When Not",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=-dfelYwd8IA",
    completed: false,
  },
  {
    id: "d4-01",
    title: "D4-01 Arithmetic Sequences: Introducing Arithmetic Sequences",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=A3_bVGyzoe4",
    completed: false,
  },
  {
    id: "d4-02",
    title: "D4-02 Arithmetic Sequences: Finding the nth term",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=lTjoZKAU23I",
    completed: false,
  },
  {
    id: "d4-03",
    title: "D4-03 Arithmetic Sequences: Finding the 2300th term",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Sv7hsMYfXX8",
    completed: false,
  },
  {
    id: "d4-04",
    title: "D4-04 Arithmetic Sequences: How many terms are there?",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Std6Gsmzktc",
    completed: false,
  },
  {
    id: "d4-05",
    title: "D4-05 Arithmetic Sequences: A Sequences Problem",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=L-tfnKI-J10&feature=youtu.be",
    completed: false,
  },
  {
    id: "d4-06",
    title: "D4-06 Arithmetic Sequences: Introducing Arithmetic Series",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=7zDVw3DHXOA&feature=youtu.be",
    completed: false,
  },
  {
    id: "d4-07",
    title: "D4-07 Arithmetic Sequences: Examples of Finding the Sum of Arithmetic Series",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=n1exKzhI1aQ",
    completed: false,
  },
  {
    id: "d4-08",
    title: "D4-08 Arithmetic Sequences: Words to Algebra",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=2s6va4MCofs",
    completed: false,
  },
  {
    id: "d4-09",
    title: "D4-09 Arithmetic Sequences: 4th term is 9, 20th term is 73",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=jE1hN7H9JH4",
    completed: false,
  },
  {
    id: "d4-10",
    title: "D4-10 Arithmetic Sequences: 21st term is 118, Sum of the first 132 terms is 48609",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=C-V9Yof5T-0",
    completed: false,
  },
  {
    id: "d4-11",
    title: "D4-11 Arithmetic Sequences: Sum of 1st-10th is 506.5, Sum of 8th-16th is 321.3",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=PglX8hgbKbQ",
    completed: false,
  },
  {
    id: "d5-01",
    title: "D5-01 Geometric Sequences: Introducing Geometric Sequences",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=QX1QjCsdPug",
    completed: false,
  },
  {
    id: "d5-02",
    title: "D5-02 Geometric Sequences: Finding the nth term",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=BuuZuqItPzM",
    completed: false,
  },
  {
    id: "d5-03",
    title: "D5-03 Geometric Sequences: Finding the 13th term",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=wjGpzKREZqU",
    completed: false,
  },
  {
    id: "d5-04",
    title: "D5-04 Geometric Sequences: How many terms are there?",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=YcEUyIasv4s",
    completed: false,
  },
  {
    id: "d5-05",
    title: "D5-05 Geometric Sequences: A Sequences Problem",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=MvrwGSzedIg&feature=youtu.be",
    completed: false,
  },
  {
    id: "d5-06",
    title: "D5-06 Geometric Sequences: Introducing Geometric Series",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=XzxoPb7Fxv0",
    completed: false,
  },
  {
    id: "d5-07",
    title: "D5-07 Geometric Sequences: Examples of Finding the Sum of Geometric Series",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=_rd680RBta0",
    completed: false,
  },
  {
    id: "d5-08",
    title: "D5-08 Geometric Sequences: Introducing Summing to Infinity",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Ud0vZp7RPx4",
    completed: false,
  },
  {
    id: "d5-09",
    title: "D5-09 Geometric Sequences: Examples of Finding the Sum to Infinity",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=pifaVehbuTY",
    completed: false,
  },
  {
    id: "d5-10",
    title: "D5-10 Geometric Sequences: Words to Algebra",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=BMfFbRP_O3U",
    completed: false,
  },
  {
    id: "d5-11",
    title: "D5-11 Geometric Sequences: 3rd term is 16, 6th term is 1.024",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=2bVlvZ_FlRE",
    completed: false,
  },
  {
    id: "d5-12",
    title: "D5-12 Geometric Sequences: Sum of 1st & 2nd is 1080, Sum of 4th & 5th is 8.64",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=LfzdWGJqbYw",
    completed: false,
  },
  {
    id: "d5-13",
    title: "D5-13 Geometric Sequences: 4th term is 24, Sum of the first 4 terms is 21",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=jHXDMK7-w4Q",
    completed: false,
  },
  {
    id: "d5-14",
    title: "D5-14 Geometric Sequences: 2nd term is 4, Sum to Infinity is 25",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Ra0G3oLy2xk",
    completed: false,
  },
  {
    id: "d5-15",
    title: "D5-15 Geometric Sequences: Exam-Style Problem",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=Uu0OqeZeQSI",
    completed: false,
  },
  {
    id: "d6-01",
    title: "D6-01 Modelling with Sequences: The Gardener Problem",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=bvx_0BIZdZ8",
    completed: false,
  },
  {
    id: "d6-02",
    title: "D6-02 Modelling with Sequences: The Medicine Problem",
    category: "sequences & series",
    url: "https://www.youtube.com/watch?v=1NFiDyPAVGM",
    completed: false,
  },

  // Trigonometry
  {
    id: "e1-15",
    title: "E1-15 Trigonometry: Introducing Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=nzGDeZS2FF0",
    completed: false,
  },
  {
    id: "e1-16",
    title: "E1-16 Trigonometry: Converting Between Degrees and Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=jodOC39uf8k",
    completed: false,
  },
  {
    id: "e1-17",
    title: "E1-17 Trigonometry: Deriving a Formula for Arc Length in Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=-qp57SnnS8E",
    completed: false,
  },
  {
    id: "e1-18",
    title: "E1-18 Trigonometry: Using the Formula for Arc Length in Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=vULd_UA2N_0",
    completed: false,
  },
  {
    id: "e1-19",
    title: "E1-19 Trigonometry: Deriving a Formula for Sector Area in Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=GARPV9zxse8",
    completed: false,
  },
  {
    id: "e1-20",
    title: "E1-20 Trigonometry: Using the Formula for Area of a Sector in Radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=TEq-2fSDWvk",
    completed: false,
  },
  {
    id: "e2-01",
    title: "E2-01 Small-Angle Approximation: Geometrical Derivation",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=I8WYe64BTQM",
    completed: false,
  },
  {
    id: "e2-02",
    title: "E2-02 Small-Angle Approximation: EXTENSION Taylor Series Derivation",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=ihYt1JrDCuM",
    completed: false,
  },
  {
    id: "e2-03",
    title: "E2-03 Small-Angle Approximation: Approximate sin(π/12), cos(π/12) & tan(π/12)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=5O2VNVPiYl0",
    completed: false,
  },
  {
    id: "e2-04",
    title: "E2-04 Small-Angle Approximation: Approximate sin(10°), cos(10°) & tan(10°)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=-TOxhGnvBv0",
    completed: false,
  },
  {
    id: "e2-05",
    title: "E2-05 Small-Angle Approximation: Percentage Error Investigation",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=4k97K-93vDo",
    completed: false,
  },
  {
    id: "e2-06",
    title: "E2-06 Small-Angle Approximation: Trig Functions as Polynomials",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=GNFaYUt0K2c",
    completed: false,
  },
  {
    id: "e3-09",
    title: "E3-09 Trig Graphs: Two Triangles in Radians to Learn",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=OczmqBLMZfw",
    completed: false,
  },
  {
    id: "e3-10",
    title: "E3-10 Trig Graphs: Testing Yourself on Exact Values of sin(x), cos(x) & tan(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=acP2JFAhMRU",
    completed: false,
  },
  {
    id: "e3-11",
    title: "E3-11 Trig Graphs: Quickly Sketching y = sin(x) in radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=M7V1mfQPpI0",
    completed: false,
  },
  {
    id: "e3-12",
    title: "E3-12 Trig Graphs: Quickly Sketching y = cos(x) in radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=qylz9RJjICg",
    completed: false,
  },
  {
    id: "e3-13",
    title: "E3-13 Trig Graphs: Quickly Sketching y = tan(x) in radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=UOdaflTetjo",
    completed: false,
  },
  {
    id: "e4-01",
    title: "E4-01 Trigonometry: Introducing cosec(x), sec(x) & cot(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=zXRy32ahN94",
    completed: false,
  },
  {
    id: "e4-02",
    title: "E4-02 Trigonometry: Given sin(x) = 3/7, exact values of cosec(x), sec(x) & cot(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=hlvrn0oXMKA",
    completed: false,
  },
  {
    id: "e4-03",
    title: "E4-03 Trigonometry: Sketching y = cosec(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=G_uMy_H1rRM",
    completed: false,
  },
  {
    id: "e4-04",
    title: "E4-04 Trigonometry: Sketching y = sec(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=7EepYzX8P-4",
    completed: false,
  },
  {
    id: "e4-05",
    title: "E4-05 Trigonometry: Sketching y = cot(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=SYOySHaQ_xQ&feature=youtu.be",
    completed: false,
  },
  {
    id: "e4-06",
    title: "E4-06 Trigonometry: Transformations of y = cosec(x), y = sec(x) & y = cot(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=a7FKjObkqns",
    completed: false,
  },
  {
    id: "e4-07",
    title: "E4-07 Trigonometry: Why we Restrict the Domain to find an Inverse Function",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=QwK97x9xZSQ",
    completed: false,
  },
  {
    id: "e4-08",
    title: "E4-08 Trigonometry: Introducing Arcsin(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=YPgh0UVydR8",
    completed: false,
  },
  {
    id: "e4-09",
    title: "E4-09 Trigonometry: Introducing Arccos(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=fTymhGSYdns",
    completed: false,
  },
  {
    id: "e4-10",
    title: "E4-10 Trigonometry: Introducing Arctan(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=zl8F4M4zVwg",
    completed: false,
  },
  {
    id: "e4-11",
    title: "E4-11 Trigonometry: Transformations of Arcsin(x), Arccos(x) & Arctan(x)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=siJRi__rueY",
    completed: false,
  },
  {
    id: "e4-12",
    title: "E4-12 Trigonometry: cos(arcsin(x)), tan(arccos(x)), cos(arctan(x))",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=y7G1Jo0qfOE",
    completed: false,
  },
  {
    id: "e5-04",
    title: "E5-04 Trigonometric Identities: arcsin(x) = arccos(y)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=IUV2FVWnW0E",
    completed: false,
  },
  {
    id: "e5-05",
    title: "E5-05 Trigonometric Identities: Proving sec^2 θ = 1 + tan^2 θ",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=YXTAotqt2iI",
    completed: false,
  },
  {
    id: "e5-06",
    title: "E5-06 Trigonometric Identities: Proving cosec^2 θ = 1 + cot^2 θ",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=mTxBRhkup2I",
    completed: false,
  },
  {
    id: "e5-07",
    title: "E5-07 Trigonometric Identities: Simplifying Further Expressions",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=E1KpnxtKKCI",
    completed: false,
  },
  {
    id: "e6-01",
    title: "E6-01 Compound Angles: Proving the Compound Angle Formulae",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=KaxRZkO0aPY&feature=youtu.be",
    completed: false,
  },
  {
    id: "e6-02",
    title: "E6-02 Compound Angles: Exact Values of sin(105°), cos(150°) & tan(15°)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=13bi_8X-SnQ",
    completed: false,
  },
  {
    id: "e6-03",
    title: "E6-03 Compound Angles: Using the Formulae Backwards",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=CZ7MLbOrWM8",
    completed: false,
  },
  {
    id: "e6-04",
    title: "E6-04 Compound Angles: Introducing the Double Angle Formulae",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=9GmeJEPTXJo",
    completed: false,
  },
  {
    id: "e6-05",
    title: "E6-05 Compound Angles: Using Double Angle Formulae to Integrate",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=mQZcZLVHM6I",
    completed: false,
  },
  {
    id: "e6-06",
    title: "E6-06 Compound Angles: Using Double Angle Formulae to Solve Equations",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=uq4QglgO1Og",
    completed: false,
  },
  {
    id: "e6-07",
    title: "E6-07 Compound Angles: More Equations using Double Angle Formulae",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=kF6OdKsD1Qc&feature=youtu.be",
    completed: false,
  },
  {
    id: "e6-08",
    title: "E6-08 Compound Angles: EXTENSION Triple Angle Formulae",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=-NDRnVQHm7s",
    completed: false,
  },
  {
    id: "e6-09",
    title: "E6-09 Equivalent Forms: Writing acosθ + bsinθ in the form rcos(θ±α) or rsin(θ±α)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=Nfyfp0dP9io",
    completed: false,
  },
  {
    id: "e6-10",
    title: "E6-10 Equivalent Forms: Writing 4cosθ + 3sinθ in the form rsin(θ+ɑ)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=DTVEBXRE1Zo",
    completed: false,
  },
  {
    id: "e6-11",
    title: "E6-11 Equivalent Forms: Writing 3cosθ - 8sinθ in the form rcos(θ+ɑ)",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=qFDuV-DoFTc",
    completed: false,
  },
  {
    id: "e6-12",
    title: "E6-12 Equivalent Forms: Solve 10sinθ - 6cosθ = 5",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=WmLWSGXGc08&feature=youtu.be",
    completed: false,
  },
  {
    id: "e6-13",
    title: "E6-13 Equivalent Forms: Maximums and Minimums",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=mobRvZmciVE&feature=youtu.be",
    completed: false,
  },
  {
    id: "e6-14",
    title: "E6-14 Equivalent Forms: Solve 2sin(2x) + 3cos(2x) = 1",
    category: "trigonometry",
    url: "https://youtu.be/2WnlfKsS5kE",
    completed: false,
  },
  {
    id: "e7-02",
    title: "E7-02 Trig Equations: Solve sin(x) = 1/2 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=Gy-0Y26IH4M&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-04",
    title: "E7-04 Trig Equations: Solve cos(x) = 1/2 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=TcMMwWHd7S0",
    completed: false,
  },
  {
    id: "e7-06",
    title: "E7-06 Trig Equations: Solve tan(x) = 1 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=LqeC9oolcUc",
    completed: false,
  },
  {
    id: "e7-08",
    title: "E7-08 Trig Equations: Solving Basic Trigonometric Equations in radians",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=OK_JwcuQ6N0",
    completed: false,
  },
  {
    id: "e7-11",
    title: "E7-11 Trig Equations: Solve 1/cos(x) = 5 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=vaNdKwpdE2Y&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-12",
    title: "E7-12 Trig Equations: Solve 1/cos(x) = 5 between 2π and 4π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=1EZwfLxE0Tg&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-14",
    title: "E7-14 Trig Equations: Solve sin^2(x) = 1/16 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=FGUeipWggHE&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-17",
    title: "E7-17 Trig Equations: Solve 4sin^2(x) = sin(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=2qsz8zn8JI0",
    completed: false,
  },
  {
    id: "e7-19",
    title: "E7-19 Trig Equations: Solve 4sin(x) + 5cos(x) = 0 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=dorc3Yzs1Wg&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-22",
    title: "E7-22 Trig Equations: Solve sin(x + π/3) = 0.7 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=LO1ZNVVF1cs",
    completed: false,
  },
  {
    id: "e7-24",
    title: "E7-24 Trig Equations: Solve cos(x - π/4) = -0.3 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=d_yy9BFz7U0",
    completed: false,
  },
  {
    id: "e7-26",
    title: "E7-26 Trig Equations: Solve tan(x + 3π) = 4.1 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=FxDYItZ0qnk",
    completed: false,
  },
  {
    id: "e7-28",
    title: "E7-28 Trig Equations: Solve sin(2x) = 0.8 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=OUCr5XUFq1Q&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-30",
    title: "E7-30 Trig Equations: Solve cos(3x) = 0.7 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=ypYCvS87Rm0&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-32",
    title: "E7-32 Trig Equations: Solve tan(4x) = 3.3 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=D0eyzDn7CYo&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-34",
    title: "E7-34 Trig Equations: Solve sin(3x-0.8) = 0.25 between π and 3π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=e1iUGkvy718",
    completed: false,
  },
  {
    id: "e7-36",
    title: "E7-36 Trig Equations: Solve sin^2(x) + 2sin(x) - 3 = 0 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=HNAp9_dbEnQ&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-38",
    title: "E7-38 Trig Equations: Solve 5tan^2(x) - 38tan(x) - 16 = 0 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=-MRSgkt2qGI&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-40",
    title: "E7-40 Trig Equations: Solve 3sin^2(x) = 3 - 2cos(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=G74MzWACDO0&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-42",
    title: "E7-42 Trig Equations: Solve 3sin(x) = 2cos^2(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=RBnzJRA_gVk&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-44",
    title: "E7-44 Trig Equations: Solve 7sin^2(x) - 5sin(x) + cos^2(x) = 0 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=lYZz-Ri1LDA&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-47",
    title: "E7-47 Trig Equations: Solve cos(x + π/3) = sin(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=UfBbHRrKc-k&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-49",
    title: "E7-49 Trig Equations: Solve sin(x - π/7) = cos(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=twoxykbiGEY&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-50",
    title: "E7-50 Trig Equations: Solve cosec(x) = 5 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=bdv75WuXB54&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-51",
    title: "E7-51 Trig Equations: Solve sec(x) = 7 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=abX4DYEygos",
    completed: false,
  },
  {
    id: "e7-52",
    title: "E7-52 Trig Equations: Solve cot(x) = 1/6 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=ro4HXwGQr6M",
    completed: false,
  },
  {
    id: "e7-53",
    title: "E7-53 Trig Equations: Solve sec^2(x) = 4 + 2tan(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=qn7PmrFQPxw&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-54",
    title: "E7-54 Trig Equations: Solve cosec^2(x) = 3cot(x) + 5 between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=8OPKgbPc_rY",
    completed: false,
  },
  {
    id: "e7-55",
    title: "E7-55 Trig Equations: Solve sec(x) = tan(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=eBnMuBvTlDQ&feature=youtu.be",
    completed: false,
  },
  {
    id: "e7-56",
    title: "E7-56 Trig Equations: Solve sin(x) = cot(x) between 0 and 2π",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=22lgLNrGbjw&feature=youtu.be",
    completed: false,
  },
  {
    id: "e8-01",
    title: "E8-01 Proving Trigonometric Identities: The Methods",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=-HAJ7VnzRrc",
    completed: false,
  },
  {
    id: "e8-02",
    title: "E8-02 Proving Trigonometric Identities: Example 1",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=5dHES1YVq3E",
    completed: false,
  },
  {
    id: "e8-03",
    title: "E8-03 Proving Trigonometric Identities: Example 2",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=ZWE_GYPdjQY",
    completed: false,
  },
  {
    id: "e8-04",
    title: "E8-04 Proving Trigonometric Identities: Example 3",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=KNIOfWe3MtI",
    completed: false,
  },
  {
    id: "e8-05",
    title: "E8-05 Proving Trigonometric Identities: Example 4",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=R6FytISnhZ8",
    completed: false,
  },
  {
    id: "e8-06",
    title: "E8-06 Proving Trigonometric Identities: Example 5",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=1X9YenjlSfo",
    completed: false,
  },
  {
    id: "e9-01",
    title: "E9-01 Trigonometry in Context: The Canoe Problem",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=y6-1sX5XQTY",
    completed: false,
  },
  {
    id: "e9-02",
    title: "E9-02 Trigonometry in Context: The Two Particles Problem",
    category: "trigonometry",
    url: "https://www.youtube.com/watch?v=aBAaxlmGKzw",
    completed: false,
  },

  // Logarithmic and Exponential Functions
  {
    id: "f1-14",
    title: "F1-14 Exponentials: EXTENSION Maximise (20/x)^x",
    category: "logarithmic",
    url: "https://www.youtube.com/watch?v=H8EAm6G3mHc&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=402",
    completed: false,
  },
  {
    id: "f1-16",
    title: "F1-16 Exponentials: EXTENSION e as an Infinite Series",
    category: "logarithmic",
    url: "https://www.youtube.com/watch?v=Qat_8Mhjkco&feature=youtu.be",
    completed: false,
  },

  // Differentiation
  {
    id: "g1-16",
    title: "G1-16 Differentiation: Differentiate sin(x) from First Principles",
    category: "differentiation",
    url: "https://youtu.be/1fsvZBy0m3Q",
    completed: false,
  },
  {
    id: "g1-17",
    title: "G1-17 Differentiation: Differentiate cos(x) from First Principles",
    category: "differentiation",
    url: "https://youtu.be/XvRfWBUGoHc",
    completed: false,
  },
  {
    id: "g1-18",
    title: "G1-18 Differentiation: Differentiate sin(x) from First Principles using Limits",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=J5fIhDHsY_Y",
    completed: false,
  },
  {
    id: "g1-19",
    title: "G1-19 Differentiation: Differentiate cos(x) from First Principles using Limits",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=K3GVfWB9gJM",
    completed: false,
  },
  {
    id: "g1-20",
    title: "G1-20 Differentiation: Convex & Concave / Concave Up & Concave Down",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=x5YidHm2uEU",
    completed: false,
  },
  {
    id: "g1-21",
    title: "G1-21 Differentiation: Convexity & The Second Derivative",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=tIag5K7pqJc",
    completed: false,
  },
  {
    id: "g2-06",
    title: "G2-06 Differentiation: Differentiating e^(kx)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=5JNBFgIE4CA",
    completed: false,
  },
  {
    id: "g2-07",
    title: "G2-07 Differentiation: Differentiating a^(kx)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=T3VsRATXnLo",
    completed: false,
  },
  {
    id: "g2-08",
    title: "G2-08 Differentiation: Differentiating sin(kx) and cos(kx)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=mBCf9rC3xiw",
    completed: false,
  },
  {
    id: "g2-09",
    title: "G2-09 Differentiation: Differentiating tan(kx)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=I0lLn4BhRY0",
    completed: false,
  },
  {
    id: "g2-10",
    title: "G2-10 Differentiation: Differentiating ln(kx)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=975NSDtkqoE",
    completed: false,
  },
  {
    id: "g3-04",
    title: "G3-04 Gradients: Equations of Tangents",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=mBksSNPrtJE",
    completed: false,
  },
  {
    id: "g3-06",
    title: "G3-06 Gradients: Equations of Normals",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=spVoCrn9xnE",
    completed: false,
  },
  {
    id: "g3-09",
    title: "G3-09 Gradients: Examples of Finding Stationary Points",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=UrFlcAhEh7g",
    completed: false,
  },
  {
    id: "g3-12",
    title: "G3-12 Gradients: The Second Derivative Test Part 2",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=htQYM7E6r2Y&feature=youtu.be",
    completed: false,
  },
  {
    id: "g3-15",
    title: "G3-15 Gradients: Determining Types of Stationary Points Example 1",
    category: "differentiation",
    url: "https://youtu.be/uQwb3AL_yg8",
    completed: false,
  },
  {
    id: "g3-16",
    title: "G3-16 Gradients: Determining Types of Stationary Points Example 2",
    category: "differentiation",
    url: "https://youtu.be/MGHUiAi90IE",
    completed: false,
  },
  {
    id: "g3-17",
    title: "G3-17 Gradients: Finding where a Curve is Convex & Concave",
    category: "differentiation",
    url: "https://youtu.be/dCLROihqi2Q",
    completed: false,
  },
  {
    id: "g3-18",
    title: "G3-18 Gradients: Examples of Convex & Concave Curves",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=G2i6D5c9-iE",
    completed: false,
  },
  {
    id: "g3-19",
    title: "G3-19 Gradients: Non-Stationary Points of Inflection Example 1",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=eLtmyCOEzsU&feature=youtu.be",
    completed: false,
  },
  {
    id: "g3-20",
    title: "G3-20 Gradients: Non-Stationary Points of Inflection Example 2",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=3geS9TjiRv8&feature=youtu.be",
    completed: false,
  },
  {
    id: "g3-21",
    title: "G3-21 Gradients: Non-Stationary Points of Inflection 3",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=32KpqD78G28&feature=youtu.be",
    completed: false,
  },
  {
    id: "g3-22",
    title: "G3-22 Gradients: Non-Stationary Points of Inflection 4 (Important)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=w-qx-s746IQ&feature=youtu.be",
    completed: false,
  },
  {
    id: "g3-23",
    title: "G3-23 Gradients: Points of Inflection of the Standard Normal Distribution",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=WRW2o_pp80Y",
    completed: false,
  },
  {
    id: "g3-24",
    title: "G3-24 Gradients: Points of Inflection of the Normal Distribution",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=WP9EmpzjZTY",
    completed: false,
  },
  {
    id: "g4-01",
    title: "G4-01 Differentiation: Introducing the Chain Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=BIu0m2DObAA",
    completed: false,
  },
  {
    id: "g4-02",
    title: "G4-02 Differentiation: Examples of using the Chain Rule Part 1 (long method)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=K7e_UpmvPn4",
    completed: false,
  },
  {
    id: "g4-03",
    title: "G4-03 Differentiation: Examples of using the Chain Rule Part 2 (short method)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=36BZPFW_mes",
    completed: false,
  },
  {
    id: "g4-04",
    title: "G4-04 Differentiation: Further Examples of using the Chain Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=AOhTkC2JcMg",
    completed: false,
  },
  {
    id: "g4-05",
    title: "G4-05 Differentiation: Introducing Connected Rates of Change",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=JHFJC0vmfU0",
    completed: false,
  },
  {
    id: "g4-06",
    title: "G4-06 Differentiation: Connected Rates of Change Example 1",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=ly_scx1YzVA",
    completed: false,
  },
  {
    id: "g4-07",
    title: "G4-07 Differentiation: Connected Rates of Change Example 2",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=uPXDWuVS1Eo",
    completed: false,
  },
  {
    id: "g4-08",
    title: "G4-08 Differentiation: Connected Rates of Change Example 3",
    category: "differentiation",
    url: "https://youtu.be/mCykQReFi00",
    completed: false,
  },
  {
    id: "g4-09",
    title: "G4-09 Differentiation: Tricky Factorisation",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=zpjNNhyGq6c",
    completed: false,
  },
  {
    id: "g4-10",
    title: "G4-10 Differentiation: Introducing the Product Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=eeXTgSniNiI",
    completed: false,
  },
  {
    id: "g4-11",
    title: "G4-11 Differentiation: EXTENSION Proof of the Product Rule",
    category: "differentiation",
    url: "https://youtu.be/r-lBvBh_KWw",
    completed: false,
  },
  {
    id: "g4-12",
    title: "G4-12 Differentiation: Examples of using the Product Rule Part 1",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=Wi2eUh-ZQ58",
    completed: false,
  },
  {
    id: "g4-13",
    title: "G4-13 Differentiation: Examples of using the Product Rule Part 2 (Factorising)",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=4MDK0-7aDeA",
    completed: false,
  },
  {
    id: "g4-14",
    title: "G4-14 Differentiation: Further Examples of using the Product Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=V8sm-1h3VC8",
    completed: false,
  },
  {
    id: "g4-15",
    title: "G4-15 Differentiation: Simplifying Algebraic Fractions",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=Qwc2ge18jc4",
    completed: false,
  },
  {
    id: "g4-16",
    title: "G4-16 Differentiation: Introducing the Quotient Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=GoxqlIrWNAY",
    completed: false,
  },
  {
    id: "g4-17",
    title: "G4-17 Differentiation: Examples of using the Quotient Rule",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=4v3ck_2h9Rk",
    completed: false,
  },
  {
    id: "g4-18",
    title: "G4-18 Differentiation: Choosing Between Rules",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=xpIr9cOyKBU",
    completed: false,
  },
  {
    id: "g4-19",
    title: "G4-19 Differentiation: Gradient Problems",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=KAadJ1MyPFk&feature=youtu.be",
    completed: false,
  },
  {
    id: "g4-20",
    title: "G4-20 Differentiation: Differentiating Cosec, Sec and Cot",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=N9K7n9Yb2Ss",
    completed: false,
  },
  {
    id: "g4-21",
    title: "G4-21 Differentiation: Differentiating an Inverse Function",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=KN-0AWHg3aM",
    completed: false,
  },
  {
    id: "g5-01",
    title: "G5-01 Differentiation: Introducing Implicit and Explicit Equations",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=97qyQGRcTgs",
    completed: false,
  },
  {
    id: "g5-02",
    title: "G5-02 Differentiation: Introducing Implicit Differentiation",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=x-_E9rX3SzY",
    completed: false,
  },
  {
    id: "g5-03",
    title: "G5-03 Differentiation: Examples of Implicit Differentiation",
    category: "differentiation",
    url: "https://youtu.be/3P4quuzo_jI",
    completed: false,
  },
  {
    id: "g5-04",
    title: "G5-04 Differentiation: Implicit Differentiation & Stationary Points",
    category: "differentiation",
    url: "https://youtu.be/6injcrZwjIE",
    completed: false,
  },
  {
    id: "g5-05",
    title: "G5-05 Differentiation: Implicit Differentiation & Parallel to the x or y axes",
    category: "differentiation",
    url: "https://youtu.be/oOAV5MMvSGc",
    completed: false,
  },
  {
    id: "g5-06",
    title: "G5-06 Differentiation: Implicit Differentiation and Gradients",
    category: "differentiation",
    url: "https://youtu.be/hNhUUAZEQwE",
    completed: false,
  },
  {
    id: "g5-07",
    title: "G5-07 Differentiation: Introducing Parametric Differentiation",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=UD-jviVsfO4",
    completed: false,
  },
  {
    id: "g5-08",
    title: "G5-08 Differentiation: Examples of Parametric Differentiation",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=HAqdAqi8Nk8",
    completed: false,
  },
  {
    id: "g5-09",
    title: "G5-09 Differentiation: Parametric Differentiation and Gradients",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=g_sGpGN_Yb8",
    completed: false,
  },
  {
    id: "g5-10",
    title: "G5-10 Differentiation: A Tricky Parametric Differentiation Problem",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=1RfkGWcKgT4",
    completed: false,
  },
  {
    id: "g6-00",
    title: "G6-00 Differential Equations: Introducing Differential Equations",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=bVdff6duXfE",
    completed: false,
  },
  {
    id: "g6-01",
    title: "G6-01 Differential Equations: Direct & Inverse Proportion",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=B_VLqgzvpdg",
    completed: false,
  },
  {
    id: "g6-02",
    title: "G6-02 Differential Equations: Examples of Forming DEs",
    category: "differentiation",
    url: "https://www.youtube.com/watch?v=EtWKWmEqNe8",
    completed: false,
  },

  // Integration
  {
    id: "h2-06",
    title: "H2-06 Integration: Integrating e^(kx)",
    category: "integration",
    url: "https://www.youtube.com/watch?v=B2ENY38hoOg",
    completed: false,
  },
  {
    id: "h2-07",
    title: "H2-07 Integration: Integrating 1/x",
    category: "integration",
    url: "https://youtu.be/mPeKfxpdyEI",
    completed: false,
  },
  {
    id: "h2-08",
    title: "H2-08 Integration: Integrating sin(kx) & cos(kx)",
    category: "integration",
    url: "https://www.youtube.com/watch?v=FJE4xDH7zb0",
    completed: false,
  },
  {
    id: "h2-09",
    title: "H2-09 Integration: Further Examples of Integration",
    category: "integration",
    url: "https://www.youtube.com/watch?v=3ACFc-LpAmM",
    completed: false,
  },
  {
    id: "h3-14",
    title: "H3-14 Integration: Finding the Area between Two Curves Example 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=M2f-o3OK0W8",
    completed: false,
  },
  {
    id: "h3-15",
    title: "H3-15 Integration: Finding the Area between Two Curves Example 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=jxSvbW7ttIU",
    completed: false,
  },
  {
    id: "h3-16",
    title: "H3-16 Integration: Finding the Area between Two Curves Example 3",
    category: "integration",
    url: "https://www.youtube.com/watch?v=Yd8klEXvvnk",
    completed: false,
  },
  {
    id: "h3-17",
    title: "H3-17 Integration: Finding the Area between Two Curves Example 4",
    category: "integration",
    url: "https://www.youtube.com/watch?v=tOBu1Svl0Wo",
    completed: false,
  },
  {
    id: "h3-18",
    title: "H3-18 Integration: Introducing Parametric Integration",
    category: "integration",
    url: "https://www.youtube.com/watch?v=R2I6QRhvrCg",
    completed: false,
  },
  {
    id: "h3-19",
    title: "H3-19 Integration: Parametric Integration Example 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=ZBIH8LVbbzQ",
    completed: false,
  },
  {
    id: "h3-20",
    title: "H3-20 Integration: Parametric Integration Example 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=4ZuG_VBJ7do",
    completed: false,
  },
  {
    id: "h4-01",
    title: "H4-01 Integration: Integration as the Limit of a Sum",
    category: "integration",
    url: "https://www.youtube.com/watch?v=5r6lBRh92tE",
    completed: false,
  },
  {
    id: "h4-02",
    title: "H4-02 Integration: An Example of finding an Area as the Limit of a Sum",
    category: "integration",
    url: "https://www.youtube.com/watch?v=nTU-qatNJvs",
    completed: false,
  },
  {
    id: "h5-01",
    title: "H5-01 Further Integration: Reversing the Chain Rule",
    category: "integration",
    url: "https://www.youtube.com/watch?v=ahKY8m2B_yA",
    completed: false,
  },
  {
    id: "h5-02",
    title: "H5-02 Further Integration: Examples of Reversing the Chain Rule Part 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=jl5B4W5BQgU",
    completed: false,
  },
  {
    id: "h5-03",
    title: "H5-03 Further Integration: More Reversing the Chain Rule",
    category: "integration",
    url: "https://www.youtube.com/watch?v=HwxB9C8yidA",
    completed: false,
  },
  {
    id: "h5-04",
    title: "H5-04 Further Integration: Examples of Reversing the Chain Rule Part 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=TP243GhryRM",
    completed: false,
  },
  {
    id: "h5-05",
    title: "H5-05 Further Integration: Reversing the Chain Rule with Trigonometry",
    category: "integration",
    url: "https://www.youtube.com/watch?v=syPqek7Aoqk",
    completed: false,
  },
  {
    id: "h5-06",
    title: "H5-06 Further Integration: Examples of Reversing the Chain Rule Part 3",
    category: "integration",
    url: "https://www.youtube.com/watch?v=b8pHrtwxhO0",
    completed: false,
  },
  {
    id: "h5-07",
    title: "H5-07 Further Integration: Reversing the Chain Rule with Exponentials",
    category: "integration",
    url: "https://www.youtube.com/watch?v=4XGTmJIYAcc",
    completed: false,
  },
  {
    id: "h5-08",
    title: "H5-08 Further Integration: Examples of Reversing the Chain Rule Part 4",
    category: "integration",
    url: "https://www.youtube.com/watch?v=K7QeDWn8dT0",
    completed: false,
  },
  {
    id: "h5-09",
    title: "H5-09 Further Integration: Reversing the Chain Rule with Reciprocals",
    category: "integration",
    url: "https://www.youtube.com/watch?v=YOPWv60MlNs",
    completed: false,
  },
  {
    id: "h5-10",
    title: "H5-10 Further Integration: Examples of Reversing the Chain Rule Part 5",
    category: "integration",
    url: "https://www.youtube.com/watch?v=svpqAJ7QNCE",
    completed: false,
  },
  {
    id: "h5-11",
    title: "H5-11 Further Integration: Why does 1/x Integrate to ln|x|+c?",
    category: "integration",
    url: "https://www.youtube.com/watch?v=vtPJdTgXOcg",
    completed: false,
  },
  {
    id: "h5-12",
    title: "H5-12 Further Integration: Introducing Integration by Substitution",
    category: "integration",
    url: "https://www.youtube.com/watch?v=GzEx5x_ph2g",
    completed: false,
  },
  {
    id: "h5-13",
    title: "H5-13 Further Integration: Examples of Integration by Substitution Part 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=HE-8zlpThL4",
    completed: false,
  },
  {
    id: "h5-14",
    title: "H5-14 Further Integration: Integrating x(2x^2 + 3)^6",
    category: "integration",
    url: "https://www.youtube.com/watch?v=eWluu4lfK5U",
    completed: false,
  },
  {
    id: "h5-15",
    title: "H5-15 Further Integration: Examples of Integration by Substitution 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=6rO9krxUCQA",
    completed: false,
  },
  {
    id: "h5-16",
    title: "H5-16 Further Integration: Integrating (2x - 5)(2x + 7)^8",
    category: "integration",
    url: "https://www.youtube.com/watch?v=kRTIvOjuxTg",
    completed: false,
  },
  {
    id: "h5-17",
    title: "H5-17 Further Integration: Examples of Integration by Substitution 3",
    category: "integration",
    url: "https://www.youtube.com/watch?v=nhkhgm5i16M&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-18",
    title: "H5-18 Further Integration: Integrating cos(x)*sin^2(x)",
    category: "integration",
    url: "https://www.youtube.com/watch?v=MA8NPfUzt5Y&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-19",
    title: "H5-19 Further Integration: Examples of Integration by Substitution 4",
    category: "integration",
    url: "https://www.youtube.com/watch?v=7TPXgVbw3uM",
    completed: false,
  },
  {
    id: "h5-20",
    title: "H5-20 Further Integration: Definite Integrals with Integration by Substitution",
    category: "integration",
    url: "https://www.youtube.com/watch?v=9nMx_RaJb3E&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-21",
    title: "H5-21 Further Integration: Examples of Definite Integrals Part 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=Gxed3qTz1TU&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-22",
    title: "H5-22 Further Integration: Examples of Definite Integrals Part 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=7j-eol-gZXc",
    completed: false,
  },
  {
    id: "h5-23",
    title: "H5-23 Further Integration: Find the Area Between Two Curves",
    category: "integration",
    url: "https://www.youtube.com/watch?v=ZVbUPoUv6D0",
    completed: false,
  },
  {
    id: "h5-24",
    title: "H5-24 Further Integration: Tricky Integration by Substitution Problems",
    category: "integration",
    url: "https://www.youtube.com/watch?v=fwCr1yS0pyw&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-25",
    title: "H5-25 Further Integration: A Tough Integration by Substitution Problem",
    category: "integration",
    url: "https://www.youtube.com/watch?v=YJIG6Ybvd4M&list=PLg2tfDG3Ww4vrstKAZ0dajHx_hq85P0G-&index=569",
    completed: false,
  },
  {
    id: "h5-26",
    title: "H5-26 Further Integration: Introducing Integration by Parts & LATE",
    category: "integration",
    url: "https://www.youtube.com/watch?v=MeHuy4OAuus&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-27",
    title: "H5-27 Further Integration: EXTENSION Deriving the Integration by Parts formula",
    category: "integration",
    url: "https://youtu.be/AbLuganvaxY",
    completed: false,
  },
  {
    id: "h5-28",
    title: "H5-28 Further Integration: When Integration by Parts goes Right",
    category: "integration",
    url: "https://www.youtube.com/watch?v=qOzW3Xp5csg&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-29",
    title: "H5-29 Further Integration: When Integration by Parts goes Wrong",
    category: "integration",
    url: "https://www.youtube.com/watch?v=76bHd-JpCoI&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-30",
    title: "H5-30 Further Integration: Integration by Parts with Definite Integrals",
    category: "integration",
    url: "https://www.youtube.com/watch?v=PBxezltZS60",
    completed: false,
  },
  {
    id: "h5-31",
    title: "H5-31 Further Integration: Examples of Integration by Parts",
    category: "integration",
    url: "https://www.youtube.com/watch?v=-ScHz5Kw8kg",
    completed: false,
  },
  {
    id: "h5-32",
    title: "H5-32 Further Integration: Integrate x*(x+1)^5 by Parts",
    category: "integration",
    url: "https://www.youtube.com/watch?v=36s7cxp5vyg&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-33",
    title: "H5-33 Further Integration: Integrating ln(x)",
    category: "integration",
    url: "https://www.youtube.com/watch?v=y6X4PYxdGU8&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-34",
    title: "H5-34 Further Integration: Integrating by Parts Twice",
    category: "integration",
    url: "https://www.youtube.com/watch?v=QSg9Js7J7ds&feature=youtu.be",
    completed: false,
  },
  {
    id: "h5-35",
    title: "H5-35 Further Integration: Integration by Parts Twice Example 1",
    category: "integration",
    url: "https://youtu.be/LTF4riUONNI",
    completed: false,
  },
  {
    id: "h5-36",
    title: "H5-36 Further Integration: Integration by Parts Twice Example 2",
    category: "integration",
    url: "https://youtu.be/011TC_qOvjU",
    completed: false,
  },
  {
    id: "h5-37",
    title: "H5-37 Further Integration: Integration by Parts Twice Example 3",
    category: "integration",
    url: "https://youtu.be/LTF4riUONNI",
    completed: false,
  },
  {
    id: "h5-38",
    title: "H5-38 Further Integration: Tabular Method for Integration by Parts",
    category: "integration",
    url: "https://www.youtube.com/watch?v=foRb72TQ4s4",
    completed: false,
  },
  {
    id: "h5-39",
    title: "H5-39 Further Integration: Examples of the Tabular Method",
    category: "integration",
    url: "https://www.youtube.com/watch?v=ahQDiVm-jME",
    completed: false,
  },
  {
    id: "h5-40",
    title: "H5-40 Further Integration: Find the Area Between Two Curves",
    category: "integration",
    url: "https://www.youtube.com/watch?v=cbIMUmfs8IE",
    completed: false,
  },
  {
    id: "h5-41",
    title: "H5-41 Further Integration: Integrate sin(x)*e^x",
    category: "integration",
    url: "https://www.youtube.com/watch?v=UHvffBhvlL0",
    completed: false,
  },
  {
    id: "h5-42",
    title: "H5-42 Further Integration: Integrating Tan and Cot",
    category: "integration",
    url: "https://www.youtube.com/watch?v=JbEjjoDuOWM",
    completed: false,
  },
  {
    id: "h5-43",
    title: "H5-43 Further Integration: EXTENSION Integrating Cosec and Sec",
    category: "integration",
    url: "https://www.youtube.com/watch?v=P49ZueWO5SM",
    completed: false,
  },
  {
    id: "h6-01",
    title: "H6-01 Integration with Partial Fractions: Example 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=VSJVe8gnAN4",
    completed: false,
  },
  {
    id: "h6-02",
    title: "H6-02 Integration with Partial Fractions: Example 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=RZxq6Ws9gUg",
    completed: false,
  },
  {
    id: "h6-03",
    title: "H6-03 Integration with Partial Fractions: Example 3",
    category: "integration",
    url: "https://www.youtube.com/watch?v=JCsxOD2BrBg&feature=youtu.be",
    completed: false,
  },
  {
    id: "h6-04",
    title: "H6-04 Integration with Partial Fractions: Example 4",
    category: "integration",
    url: "https://www.youtube.com/watch?v=3UcEGtB-PNY",
    completed: false,
  },
  {
    id: "h6-05",
    title: "H6-05 Integration with Partial Fractions: Example 5",
    category: "integration",
    url: "https://www.youtube.com/watch?v=Et1AcA_Wbjk",
    completed: false,
  },
  {
    id: "h6-06",
    title: "H6-06 Integration with Partial Fractions: Example 6",
    category: "integration",
    url: "https://www.youtube.com/watch?v=yGku6PQJxb0",
    completed: false,
  },
  {
    id: "h6-07",
    title: "H6-07 Integration with Partial Fractions: Example 7",
    category: "integration",
    url: "https://www.youtube.com/watch?v=acACFYhBlZY",
    completed: false,
  },
  {
    id: "h6-08",
    title: "H6-08 Integration with Partial Fractions: EXTENSION Example 8",
    category: "integration",
    url: "https://www.youtube.com/watch?v=ANlMDOWBLE8",
    completed: false,
  },
  {
    id: "h7-01",
    title: "H7-01 Differential Equations: Introducing Differential Equations",
    category: "integration",
    url: "https://www.youtube.com/watch?v=h9Q-_W7_YG4",
    completed: false,
  },
  {
    id: "h7-02",
    title: "H7-02 Differential Equations: The Method of Separation of Variables",
    category: "integration",
    url: "https://www.youtube.com/watch?v=5DkjYCd95ms",
    completed: false,
  },
  {
    id: "h7-03",
    title: "H7-03 Differential Equations: Examples of Finding General Solutions",
    category: "integration",
    url: "https://www.youtube.com/watch?v=H7RUfjoBmj0",
    completed: false,
  },
  {
    id: "h7-04",
    title: "H7-04 Differential Equations: Examples of Finding Particular Solutions",
    category: "integration",
    url: "https://www.youtube.com/watch?v=x3R97yXqk2g",
    completed: false,
  },
  {
    id: "h7-05",
    title: "H7-05 Differential Equations: Tougher Examples",
    category: "integration",
    url: "https://youtu.be/p2P-84C6Pw8",
    completed: false,
  },
  {
    id: "h8-01",
    title: "H8-01 Differential Equations: A Worded Example 1",
    category: "integration",
    url: "https://www.youtube.com/watch?v=v66blKhKN4g",
    completed: false,
  },
  {
    id: "h8-02",
    title: "H8-02 Differential Equations: A Worded Example 2",
    category: "integration",
    url: "https://www.youtube.com/watch?v=GUnSEXwg-A4",
    completed: false,
  },
  {
    id: "h8-03",
    title: "H8-03 Differential Equations: A Worded Example 3",
    category: "integration",
    url: "https://www.youtube.com/watch?v=JX8nxGrYMjg",
    completed: false,
  },

  // Numerical Solution of Equations
  {
    id: "i1-00",
    title: "I1-00 Locating Roots: Introducing the Need for Numerical Methods",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=EirD2_kCuQY",
    completed: false,
  },
  {
    id: "i1-01",
    title: "I1-01 Locating Roots: Introducing the Change of Sign Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=gjrOBrW5jAg",
    completed: false,
  },
  {
    id: "i1-02",
    title: "I1-02 Locating Roots: The Change of Sign Method Example 1",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=aEIFs8w9k6g",
    completed: false,
  },
  {
    id: "i1-03",
    title: "I1-03 Locating Roots: The Change of Sign Method Example 2",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=w795UMpjkXg",
    completed: false,
  },
  {
    id: "i1-04",
    title: "I1-04 Locating Roots: Failure of the Change of Sign Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=bfOpEoiUlnQ",
    completed: false,
  },
  {
    id: "i1-05",
    title: "I1-05 Locating Roots: EXTENSION Decimal Search and Bisection Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=0t96RLeBZxk",
    completed: false,
  },
  {
    id: "i2-01",
    title: "I2-01 Locating Roots: Introducing the x=g(x) Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=KYzK6da04Oo",
    completed: false,
  },
  {
    id: "i2-02",
    title: "I2-02 Locating Roots: Cobweb and Staircase Diagrams",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=gfKu1ILeVdg",
    completed: false,
  },
  {
    id: "i2-03",
    title: "I2-03 Locating Roots: The x=g(x) Method Example 1",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=TU8-vzkHcj0",
    completed: false,
  },
  {
    id: "i2-04",
    title: "I2-04 Locating Roots: The x=g(x) Method Example 2",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=fiFUYW21HX4",
    completed: false,
  },
  {
    id: "i2-05",
    title: "I2-05 Locating Roots: Failure of the x=g(x) Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=hSZfys9_LoU",
    completed: false,
  },
  {
    id: "i2-06",
    title: "I2-06 Locating Roots: Introducing the Newton-Raphson Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=ep8wI-p5Zbg",
    completed: false,
  },
  {
    id: "i2-07",
    title: "I2-07 Locating Roots: The Newton-Raphson Method Example 1",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=Eeg9HlSy9JA",
    completed: false,
  },
  {
    id: "i2-08",
    title: "I2-08 Locating Roots: The Newton-Raphson Method Example 2",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=5m7rICN9OkE",
    completed: false,
  },
  {
    id: "i2-09",
    title: "I2-09 Locating Roots: Failure of the Newton-Raphson Method",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=d4TtDbC0zEo",
    completed: false,
  },
  {
    id: "i2-10",
    title: "I2-10 Locating Roots: Newton-Raphson Problem",
    category: "numerical",
    url: "https://youtu.be/nz92HSr-Sf0",
    completed: false,
  },
  {
    id: "i3-01",
    title: "I3-01 Numerical Integration: Estimating using Rectangles",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=3LeeYrUHHvY",
    completed: false,
  },
  {
    id: "i3-02",
    title: "I3-02 Numerical Integration: Estimating using Trapeziums",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=WlQbJq5lDhU",
    completed: false,
  },
  {
    id: "i3-03",
    title: "I3-03 Numerical Integration: Introducing the Trapezium Rule",
    category: "numerical",
    url: "https://youtu.be/3zueEN_CSOQ",
    completed: false,
  },
  {
    id: "i3-04",
    title: "I3-04 Numerical Integration: Examples of Using the Trapezium Rule",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=wn-ZhDtAVS0",
    completed: false,
  },
  {
    id: "i3-05",
    title: "I3-05 Numerical Integration: Overestimate or Underestimate?",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=IQEe5AUUxd4",
    completed: false,
  },
  {
    id: "i3-06",
    title: "I3-06 Numerical Integration: EXTENSION Monte Carlo Integration",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=xS7beVDhhfw",
    completed: false,
  },
  {
    id: "i4-01",
    title: "I4-01 Numerical Methods: Contextual Problem 1",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=PwHIWoJsjoo",
    completed: false,
  },
  {
    id: "i4-02",
    title: "I4-02 Numerical Methods: Contextual Problem 2",
    category: "numerical",
    url: "https://www.youtube.com/watch?v=gersaQznLcs",
    completed: false,
  },

  // Vectors
  {
    id: "j1-05",
    title: "J1-05 Vectors: Introducing 3D Vectors",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=n-8x9wbCJj4",
    completed: false,
  },
  {
    id: "j2-09",
    title: "J2-09 Vectors: Finding the Magnitude / Length of a 3D vector",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=qz5RxiP61Aw",
    completed: false,
  },
  {
    id: "j2-10",
    title: "J2-10 Vectors: Examples of Finding the Magnitude of 3D Vectors",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=Yy-3Igc89us",
    completed: false,
  },
  {
    id: "j2-11",
    title: "J2-11 Vectors: Finding the Angle between Two 3D Vectors Method 1",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=EsvM6cI5kDk",
    completed: false,
  },
  {
    id: "j2-12",
    title: "J2-12 Vectors: Finding the Angle between Two 3D Vectors Method 2",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=RJHyvpeHgKM",
    completed: false,
  },
  {
    id: "j5-05",
    title: "J5-05 Vectors: Kinematics Problem",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=HUhAJoVlUus",
    completed: false,
  },
  {
    id: "j5-06",
    title: "J5-06 Vectors: 3D Vectors Problem",
    category: "vectors",
    url: "https://www.youtube.com/watch?v=BQpAUOchYdk",
    completed: false,
  },

  // Probability
  {
    id: "m2-01",
    title: "M2-01 Probability: Introducing Conditional Probability",
    category: "probability",
    url: "https://www.youtube.com/watch?v=xU16N2kj0ko",
    completed: false,
  },
  {
    id: "m2-02",
    title: "M2-02 Probability: Conditional Probability Formulae",
    category: "probability",
    url: "https://www.youtube.com/watch?v=6iySd1rMDxs",
    completed: false,
  },
  {
    id: "m2-03",
    title: "M2-03 Probability: Determining whether Two Events are Independent",
    category: "probability",
    url: "https://www.youtube.com/watch?v=MafsUKzMKhE",
    completed: false,
  },
  {
    id: "m2-04",
    title: "M2-04 Probability: Venn Diagram Example",
    category: "probability",
    url: "https://www.youtube.com/watch?v=25PJV39zPyU",
    completed: false,
  },
  {
    id: "m2-05",
    title: "M2-05 Probability: Tree Diagram Example",
    category: "probability",
    url: "https://www.youtube.com/watch?v=cOjz6JMAWjI",
    completed: false,
  },
  {
    id: "m2-06",
    title: "M2-06 Probability: Two-Way Table Example",
    category: "probability",
    url: "https://www.youtube.com/watch?v=ps0X0RmLTYQ",
    completed: false,
  },
  {
    id: "m2-07",
    title: "M2-07 Probability: 3-Circle Venn Diagram",
    category: "probability",
    url: "https://youtu.be/kLVPYCPyZAk",
    completed: false,
  },
  {
    id: "m3-01",
    title: "M3-01 Modelling with Probability: Binomial Distribution",
    category: "probability",
    url: "https://www.youtube.com/watch?v=ebUTONrpE2E",
    completed: false,
  },
  {
    id: "m3-02",
    title: "M3-02 Modelling with Probability: Normal Distribution",
    category: "probability",
    url: "https://www.youtube.com/watch?v=hYujWcAJReI",
    completed: false,
  },

  // Statistical distributions
  {
    id: "n1-21",
    title: "N1-21 Binomial Distribution: Mean and Variance",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=7ZhRhex-8E8",
    completed: false,
  },
  {
    id: "n2-01",
    title: "N2-01 Normal Distribution: Introducing the Bell Curve",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=x1tSnYQLv9I",
    completed: false,
  },
  {
    id: "n2-02",
    title: "N2-02 Normal Distribution: Introducing the Normal Distribution",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=5b6AM-enBPo",
    completed: false,
  },
  {
    id: "n2-03",
    title: "N2-03 Normal Distribution: Finding Probabilities Example 1",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=uoujOf3JheU",
    completed: false,
  },
  {
    id: "n2-04",
    title: "N2-04 Normal Distribution: Finding Probabilities Example 2",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=HwW66x9wJN4",
    completed: false,
  },
  {
    id: "n2-05",
    title: "N2-05 Normal Distribution: A Worded Problem 1",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=LqFajCfSlVk",
    completed: false,
  },
  {
    id: "n2-06",
    title: "N2-06 Normal Distribution: The Inverse Normal",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=M4WvzYIuVE4",
    completed: false,
  },
  {
    id: "n2-07",
    title: "N2-07 Normal Distribution: Inverse Normal Example",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=x5aWDVW5bQ0",
    completed: false,
  },
  {
    id: "n2-08",
    title: "N2-08 Normal Distribution: Simultaneous Equations",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=syCImJQdqn0",
    completed: false,
  },
  {
    id: "n2-09",
    title: "N2-09 Normal Distribution: A Worded Problem 2",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=bok6ND7Qn9E",
    completed: false,
  },
  {
    id: "n2-10",
    title: "N2-10 Normal Distribution: Normal to Binomial Problem",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=jcOl4AKXyWc",
    completed: false,
  },
  {
    id: "n2-11",
    title: "N2-11 Normal Distribution: Normal to Histogram",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=C1SytMIHMvE",
    completed: false,
  },
  {
    id: "n2-12",
    title: "N2-12 Normal Distribution: Approximating a Binomial Distribution",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=GREDEOsAO2A",
    completed: false,
  },
  {
    id: "n2-13",
    title: "N2-13 Normal Distribution: Continuity Correction Examples",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=1wa4jSYSGh4",
    completed: false,
  },
  {
    id: "n2-14",
    title: "N2-14 Normal Distribution: Approximating a Binomial Example",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=misbUlbe0sU",
    completed: false,
  },
  {
    id: "n3-01",
    title: "N3-01 Probability Distributions: Appropriate Distributions",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=1j6NnJZf6MQ",
    completed: false,
  },
  {
    id: "n3-02",
    title: "N3-02 Probability Distributions: Approximating μ and σ",
    category: "statistical distributions",
    url: "https://www.youtube.com/watch?v=Eoj5npFC4w4",
    completed: false,
  },

  // Statistical hypothesis testing
  {
    id: "o1-05",
    title: "O1-05 Hypothesis Testing: PMCC Introduction",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=u9qI49EG2UY",
    completed: false,
  },
  {
    id: "o1-06",
    title: "O1-06 Hypothesis Testing: PMCC Example 1",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=sKC9j4vN4fY",
    completed: false,
  },
  {
    id: "o1-07",
    title: "O1-07 Hypothesis Testing: PMCC Example 2",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=8PUcAuGjZVo",
    completed: false,
  },
  {
    id: "o1-08",
    title: "O1-08 Hypothesis Testing: PMCC Example 3",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=Z7t_a0_ePnk",
    completed: false,
  },
  {
    id: "o1-09",
    title: "O1-09 Hypothesis Testing: OCR MEI ONLY Rank Correlation",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=nV3-H4wVgkc",
    completed: false,
  },
  {
    id: "o1-10",
    title: "O1-10 Hypothesis Testing: OCR MEI ONLY Rank Correlation Example 1",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=NV1N6WWznyY",
    completed: false,
  },
  {
    id: "o1-11",
    title: "O1-11 Hypothesis Testing: OCR MEI ONLY Rank Correlation Example 2",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=c6ERZDzAu9o",
    completed: false,
  },
  {
    id: "o1-12",
    title: "O1-12 Hypothesis Testing: OCR MEI ONLY Rank Correlation Example 3",
    category: "statistical hypothesis testing",
    url: "https://www.youtube.com/watch?v=32nQTdgb3lo",
    completed: false,
  },
  {
    id: "o3-01",
    title: "O3-01 Introducing Sample Means Hypothesis Testing",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/M13X5JYWgcc",
    completed: false,
  },
  {
    id: "o3-02",
    title: "O3-02 Three Methods for Sample Means Hypothesis Testing",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/hWqttH2VrUs",
    completed: false,
  },
  {
    id: "o3-03",
    title: "O3-03 Sample Means Hypothesis Testing Example 1 - p-value Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/s9DHGuYC5s8",
    completed: false,
  },
  {
    id: "o3-04",
    title: "O3-04 Sample Means Hypothesis Testing Example 1 - Critical Region Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/v2GDHZx9JuI",
    completed: false,
  },
  {
    id: "o3-05",
    title: "O3-05 Sample Means Hypothesis Testing Example 1 - Test Statistic Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/bLVq6x4hyxM",
    completed: false,
  },
  {
    id: "o3-06",
    title: "O3-06 Sample Means Hypothesis Testing Example 2 - p-value Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/P7_f1DFBtlU",
    completed: false,
  },
  {
    id: "o3-07",
    title: "O3-07 Sample Means Hypothesis Testing Example 2 - Critical Region Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/ByIJaZrgmMQ",
    completed: false,
  },
  {
    id: "o3-08",
    title: "O3-08 Sample Means Hypothesis Testing Example 2 - Test Statistic Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/_oGyCtDraTk",
    completed: false,
  },
  {
    id: "o3-09",
    title: "O3-09 Sample Means Hypothesis Testing Example 3 - p-value Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/rQU3k8a9iTs",
    completed: false,
  },
  {
    id: "o3-10",
    title: "O3-10 Sample Means Hypothesis Testing Example 3 - Critical Region Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/BxOL8B-hd24",
    completed: false,
  },
  {
    id: "o3-11",
    title: "O3-11 Sample Means Hypothesis Testing Example 3 - Test Statistic Method",
    category: "statistical hypothesis testing",
    url: "https://youtu.be/zx5hzIUEQjc",
    completed: false,
  },

];
